### PR TITLE
React + CoffeeScript

### PR DESCRIPTION
**Pull request by kulicuu**
This is an interesting way of doing React + CoffeeScript I learned from Alberto Torres Ruiz. 

I'll add some more interesting GUI elements later; for now just wanted to initiate it and see if I could get it to work with SocketStream.

### CODE REVIEW

**Comment by arxpoetica** [comment]
Interesting. Looking forward to the example.

**Comment by arxpoetica** [comment]
@kulicuu you may wish to look at this example app for help: https://github.com/dozoisch/koa-react-full-example

**Comment by kulicuu** [comment]
You might want to do a different React example.  Like I said there are many
ways of doing this, mine is one of my particular derivatives of a style of
doing it I learned from someone else.  Have you found anything functionally
wrong with it ?

**Comment by kulicuu** [comment]
I may look at it though.  So much to do !!!!!!!!!!! ;)

**Comment by arxpoetica** [comment]
Ha ha you got to my comment before I deleted it! I realized that one uses Koa, which is it's own beast. I'm creating an app w/ Koa and Ractive ([there's a branch for it here](https://github.com/socketstream/ss-examples/tree/feature/ractive-example)—note, it's a work in progress, definitely not done.). I'll be curious to see what you come up with!

**Comment by kulicuu** [comment]
haha I was going to say I could rename the one I'm doing.  Mine is active
now. you can try it.  It's not very complicated yet, but open the consoles
and type in the input.  It's cool because there are no templates anymore,
but it's not JSX/CSX.  The CoffeeScript contains all the markup.  I've to
add the Stylus file and think of something to be entertaining (that's not
done yet).

**Comment by kulicuu** [comment]
I've never used Koa.  It's on that todo list I mentioned ;0

**Comment by kulicuu** [comment]
i need to close this and re-open -- trouble with node_modules folder

**Pull request closed without merging**
